package urp.model.pojos;
// Generated 19/05/2016 11:45:16 PM by Hibernate Tools 4.3.1



/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails  implements java.io.Serializable {


     private OrderdetailsId id;
     private Orders orders;
     private Products products;
     private double unitPrice;
     private short quantity;
     private double discount;

    public Orderdetails() {
    }

    public Orderdetails(OrderdetailsId id, Orders orders, Products products, double unitPrice, short quantity, double discount) {
       this.id = id;
       this.orders = orders;
       this.products = products;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.discount = discount;
    }
   
    public OrderdetailsId getId() {
        return this.id;
    }
    
    public void setId(OrderdetailsId id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(short quantity) {
        this.quantity = quantity;
    }
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }




}


